# Generated by Django 4.2.3 on 2023-07-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PVP_students_test_app.category'),
        ),
    ]
