# Generated by Django 4.2.3 on 2023-07-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0003_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PVP_students_test_app.category'),
        ),
    ]
