# Generated by Django 4.2.3 on 2023-07-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0004_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cutoff',
            field=models.IntegerField(default=100),
        ),
    ]
