# Generated by Django 4.2.3 on 2023-07-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0005_category_cutoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='subject',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.JSONField(default=[], null=True),
        ),
    ]
