# Generated by Django 4.2.3 on 2023-07-20 06:38

import PVP_students_test_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0008_alter_student_evaluation_result'),
    ]

    operations = [
        
    ]
