# Generated by Django 4.2.3 on 2023-07-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0009_alter_student_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cutoff',
            new_name='category_passing_marks',
        ),
    ]
