# Generated by Django 4.2.3 on 2023-07-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0010_rename_cutoff_category_category_passing_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_passing_marks', models.IntegerField(default=300)),
            ],
        ),
    ]
