# Generated by Django 4.2.3 on 2023-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0011_test_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_conditions',
            name='category_passing_marks',
            field=models.JSONField(default=list, null=True),
        ),
    ]
