# Generated by Django 4.2.3 on 2023-07-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0012_test_conditions_category_passing_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.JSONField(default=list, null=True),
        ),
    ]
