# Generated by Django 4.2.3 on 2023-07-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0015_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'red_hex'), ('#00FF00', 'green_hex'), ('#0000FF', 'blue_hex'), ('#800080', 'purple_hex')], max_length=10),
        ),
    ]
