# Generated by Django 4.2.3 on 2023-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0016_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#E6E6FA', 'lavender'), ('#B0E0E6', 'powderBlue'), ('#FAEBD7', 'almond'), ('#CBBEB5', 'brown')], max_length=10),
        ),
    ]
