# Generated by Django 4.2.3 on 2023-07-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0017_alter_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default_Project_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_student_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#E6E6FA', 'lavender'), ('#B0E0E6', 'powderBlue'), ('#FAEBD7', 'almond'), ('#CBBEB5', 'brown'), ('#F2EE9D', 'green'), ('#78C1F3', 'lightBlue'), ('#FFA41B', 'orange'), ('#F1D4E5', 'pink'), ('#F99B7D', 'pinkOrange')], max_length=10),
        ),
    ]
