# Generated by Django 4.2.3 on 2023-07-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PVP_students_test_app', '0018_default_project_data_alter_category_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Default_Project_Data',
        ),
    ]
